# Generated by Django 6.0.5 on 2026-05-15 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('hour', models.PositiveSmallIntegerField(help_text="Numero progressivo dell'ora nella giornata. Es: 1 per la prima ora.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Ora')),
                ('description', models.TextField(blank=True, verbose_name='Argomenti trattati')),
            ],
            options={
                'verbose_name': 'Lezione',
                'verbose_name_plural': 'Lezioni',
                'ordering': ['date', 'hour'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: 5IE, 3A, 1B', max_length=50, verbose_name='Nome classe')),
                ('school_year', models.CharField(help_text='Formato AAAA/AAAA. Es: 2024/2025', max_length=9, verbose_name='Anno scolastico')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='tenants.tenant', verbose_name='Scuola')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classi',
                'ordering': ['school_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Data inizio')),
                ('date_end', models.DateField(blank=True, help_text="Lasciare vuoto se l'iscrizione è ancora attiva.", null=True, verbose_name='Data fine')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.schoolclass', verbose_name='Classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentprofile', verbose_name='Studente')),
            ],
            options={
                'verbose_name': 'Iscrizione studente',
                'verbose_name_plural': 'Iscrizioni studenti',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: Matematica, Italiano, Fisica', max_length=100, verbose_name='Nome materia')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.tenant', verbose_name='Scuola')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Data inizio')),
                ('date_end', models.DateField(blank=True, help_text="Lasciare vuoto se l'incarico è ancora attivo.", null=True, verbose_name='Data fine')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.teacherprofile', verbose_name='Insegnante')),
            ],
            options={
                'verbose_name': 'Incarico insegnante',
                'verbose_name_plural': 'Incarichi insegnanti',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Tardiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('entry_time', models.TimeField(verbose_name='Ora di ingresso')),
                ('needs_justification', models.BooleanField(default=True, help_text='True se il ritardo richiede giustificazione scritta.', verbose_name='Da giustificare')),
                ('is_justified', models.BooleanField(default=False, verbose_name='Giustificato')),
                ('justification', models.TextField(blank=True, verbose_name='Motivazione giustifica')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tardinesses', to='core.lesson', verbose_name='Lezione di riferimento')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tardinesses', to='core.studentenrollment', verbose_name='Iscrizione studente')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_tardinesses', to='core.teacherassignment', verbose_name='Insegnante che registra')),
            ],
            options={
                'verbose_name': 'Ritardo',
                'verbose_name_plural': 'Ritardi',
                'ordering': ['-date', 'entry_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('is_disciplinary', models.BooleanField(default=False, help_text='True se la nota ha rilevanza disciplinare.', verbose_name='Disciplinare')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='core.lesson', verbose_name='Lezione di riferimento')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.studentenrollment', verbose_name='Iscrizione studente')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.teacherassignment', verbose_name='Insegnante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Note',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('is_justified', models.BooleanField(default=False, verbose_name='Giustificata')),
                ('justification', models.TextField(blank=True, verbose_name='Motivazione giustifica')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='core.lesson', verbose_name='Lezione di riferimento')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.studentenrollment', verbose_name='Iscrizione studente')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_absences', to='core.teacherassignment', verbose_name='Insegnante che registra')),
            ],
            options={
                'verbose_name': 'Assenza',
                'verbose_name_plural': 'Assenze',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.teacherassignment', verbose_name='Incarico')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_subjects', to='core.schoolclass', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_subjects', to='core.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Assegnazione classe-materia',
                'verbose_name_plural': 'Assegnazioni classe-materia',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.teacherclasssubject', verbose_name='Insegnante / Classe / Materia'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(verbose_name='Data assegnazione')),
                ('due_date', models.DateField(verbose_name='Data consegna')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_assignments', to='core.lesson', verbose_name='Lezione di riferimento')),
                ('teacher_class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='core.teacherclasssubject', verbose_name='Insegnante / Classe / Materia')),
            ],
            options={
                'verbose_name': 'Compito',
                'verbose_name_plural': 'Compiti',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, help_text='Voto da 1.00 a 10.00.', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Voto')),
                ('description', models.TextField(blank=True, help_text='Es: interrogazione orale, compito in classe, verifica scritta.', verbose_name='Descrizione')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.lesson', verbose_name='Lezione di riferimento')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.studentenrollment', verbose_name='Iscrizione studente')),
                ('teacher_class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.teacherclasssubject', verbose_name='Insegnante / Materia')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Voti',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'school_year'), name='unique_class_per_year_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_subject_per_school'),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(fields=('student_enrollment', 'date'), name='unique_absence_per_student_per_day'),
        ),
        migrations.AddConstraint(
            model_name='teacherclasssubject',
            constraint=models.UniqueConstraint(fields=('assignment', 'school_class', 'subject'), name='unique_subject_per_teacher_per_class'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('teacher_class_subject', 'date', 'hour'), name='unique_lesson_per_teacher_class_hour'),
        ),
    ]
