# Generated by Django 6.0.5 on 2026-05-15 02:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Identificatore univoco del permesso. Es: grade.create', max_length=100, unique=True, verbose_name='Codename')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Permesso',
                'verbose_name_plural': 'Permessi',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fiscal_code', models.CharField(help_text='16 caratteri alfanumerici. Unico per ogni utente.', max_length=16, unique=True, verbose_name='Codice fiscale')),
                ('birth_date', models.DateField(verbose_name='Data di nascita')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero di telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Insegnante'), ('student', 'Studente'), ('parent', 'Genitore'), ('admin', 'Amministratore')], max_length=20, verbose_name='Ruolo')),
                ('is_active', models.BooleanField(default=True, help_text='Permette di disabilitare un ruolo senza eliminarlo. Es: uno studente che si trasferisce non viene cancellato, ma il suo ruolo viene disattivato per preservare lo storico dei voti.', verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data assegnazione ruolo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='tenants.tenant', verbose_name='Scuola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Ruolo utente',
                'verbose_name_plural': 'Ruoli utenti',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='users.userrole', verbose_name='Ruolo associato')),
            ],
            options={
                'verbose_name': 'Profilo insegnante',
                'verbose_name_plural': 'Profili insegnanti',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_year', models.IntegerField(help_text="Es: 2024 per l'anno scolastico 2024/2025.", verbose_name='Anno di iscrizione')),
                ('role', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='users.userrole', verbose_name='Ruolo associato')),
            ],
            options={
                'verbose_name': 'Profilo studente',
                'verbose_name_plural': 'Profili studenti',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('mother', 'Madre'), ('father', 'Padre'), ('guardian', 'Tutore legale')], max_length=20, verbose_name='Tipo di relazione')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='users.userrole', verbose_name='Genitore')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='users.userrole', verbose_name='Studente (figlio/a)')),
            ],
            options={
                'verbose_name': 'Relazione genitore-studente',
                'verbose_name_plural': 'Relazioni genitore-studente',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='users.userrole', verbose_name='Ruolo associato')),
            ],
            options={
                'verbose_name': 'Profilo genitore',
                'verbose_name_plural': 'Profili genitori',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='users.userrole', verbose_name='Ruolo associato')),
            ],
            options={
                'verbose_name': 'Profilo amministratore',
                'verbose_name_plural': 'Profili amministratori',
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to='users.adminprofile', verbose_name='Admin')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to='users.permission', verbose_name='Permesso')),
            ],
            options={
                'verbose_name': 'Permesso admin',
                'verbose_name_plural': 'Permessi admin',
                'constraints': [models.UniqueConstraint(fields=('admin_profile', 'permission'), name='unique_admin_permission')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Insegnante'), ('student', 'Studente'), ('parent', 'Genitore'), ('admin', 'Amministratore')], max_length=20, verbose_name='Ruolo')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission', verbose_name='Permesso')),
            ],
            options={
                'verbose_name': 'Permesso per ruolo',
                'verbose_name_plural': 'Permessi per ruolo',
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission')],
            },
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'tenant', 'role'), name='unique_user_tenant_role'),
        ),
        migrations.AddConstraint(
            model_name='parentstudentrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student'),
        ),
    ]
