# Generated by Django 6.0.5 on 2026-05-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: Liceo Scientifico Einstein', max_length=200, verbose_name='Nome della scuola')),
                ('slug', models.SlugField(help_text="Versione URL-friendly del nome. Es: liceo-scientifico-einstein. Si usa negli URL per identificare la scuola in modo leggibile. Nel form admin si popola automaticamente dal campo 'name' tramite prepopulated_fields (configurato in admin.py).", max_length=100, unique=True, verbose_name='Identificatore URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
            ],
            options={
                'verbose_name': 'Scuola',
                'verbose_name_plural': 'Scuole',
                'ordering': ['name'],
            },
        ),
    ]
